Algoritmo "semnome"

Var
a,b,c,d,f,g,h,i:real

Inicio
escreva("Digite valor de a(o que esta a o quadrado): ")
leia (a)
escreva ("Digite o valor de b(oque esta acompanhado ao x): ")
leia(b)
escreva("Digite o valor de c(oque esta sozinho): ")
leia (c)
d<-b^2-4*a*c

se(0>d)entao
escreva("Resultado:conjunto vazio")
fimse
se(d>0)entao
f<-raizq(d)
g<-(-b+f)/2
h<-(-b-f)/2
i<-1
fimse
se(i=1)entao
escreva ("Resultado: ",g," e",h)
fimse
fimalgoritmo 
